"""
Tests for request ID middleware in api/main.py.

Covers:
- X-Request-ID header presence on all responses
- Client-provided X-Request-ID pass-through
- UUID format validation for auto-generated IDs
- Unique IDs per request
- request_id in health endpoint response body
"""

import uuid
import pytest
from fastapi.testclient import TestClient
from api.main import app

client = TestClient(app)


class TestRequestIDHeader:
    """Verify X-Request-ID header behaviour."""

    def test_header_present_on_health(self):
        """Every response must include an X-Request-ID header."""
        response = client.get("/health")
        assert response.status_code == 200
        assert "X-Request-ID" in response.headers
        request_id = response.headers["X-Request-ID"]
        assert len(request_id) > 0

    def test_header_present_on_agents(self):
        """X-Request-ID must appear on all endpoints, not just health."""
        response = client.get("/agents")
        assert response.status_code == 200
        assert "X-Request-ID" in response.headers

    def test_header_present_on_tasks(self):
        """X-Request-ID must appear on /tasks."""
        response = client.get("/tasks")
        assert response.status_code == 200
        assert "X-Request-ID" in response.headers

    def test_header_present_on_leaderboard(self):
        """X-Request-ID must appear on /leaderboard."""
        response = client.get("/leaderboard")
        assert response.status_code == 200
        assert "X-Request-ID" in response.headers

    def test_header_present_on_404(self):
        """X-Request-ID must appear even on error responses."""
        response = client.get("/agents/nonexistent")
        assert response.status_code == 404
        assert "X-Request-ID" in response.headers


class TestAutoGeneratedID:
    """Verify auto-generated IDs are valid UUIDs."""

    def test_auto_id_is_valid_uuid(self):
        """When no client ID is provided, generate a valid UUID v4."""
        response = client.get("/health")
        request_id = response.headers["X-Request-ID"]
        # Should parse as a UUID without raising
        parsed = uuid.UUID(request_id)
        # UUID v4 has version nibble = 4
        assert parsed.version == 4

    def test_unique_ids_per_request(self):
        """Each request must receive a different auto-generated ID."""
        ids = set()
        for _ in range(5):
            response = client.get("/health")
            ids.add(response.headers["X-Request-ID"])
        assert len(ids) == 5, "Expected 5 unique request IDs"


class TestClientPassThrough:
    """Verify client-provided X-Request-ID is preserved."""

    def test_client_id_preserved(self):
        """When client sends X-Request-ID, response must echo it back."""
        custom_id = "trace-abc-123"
        response = client.get("/health", headers={"X-Request-ID": custom_id})
        assert response.status_code == 200
        assert response.headers["X-Request-ID"] == custom_id

    def test_client_id_preserved_on_404(self):
        """Client ID must be preserved even on error responses."""
        custom_id = "error-trace-xyz"
        response = client.get(
            "/agents/nonexistent", headers={"X-Request-ID": custom_id}
        )
        assert response.status_code == 404
        assert response.headers["X-Request-ID"] == custom_id

    def test_client_id_not_validated(self):
        """Any string is accepted as a client-provided ID (no format validation)."""
        weird_id = "my-custom-tracing-id-!@#$"
        response = client.get("/health", headers={"X-Request-ID": weird_id})
        assert response.headers["X-Request-ID"] == weird_id


class TestHealthEndpointRequestID:
    """Verify request_id is included in the health endpoint response body."""

    def test_health_includes_request_id(self):
        """Health check response body must include the request_id field."""
        response = client.get("/health")
        data = response.json()
        assert "request_id" in data
        assert data["request_id"] == response.headers["X-Request-ID"]

    def test_health_request_id_matches_header(self):
        """Health response body request_id must match the header value."""
        custom_id = "health-check-42"
        response = client.get("/health", headers={"X-Request-ID": custom_id})
        data = response.json()
        assert data["request_id"] == custom_id
        assert response.headers["X-Request-ID"] == custom_id
